@file:OptIn(kotlin.time.ExperimentalTime::class)

package app.spent.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import app.spent.ServiceLocator
import app.spent.capture.CategoryMatcher
import app.spent.capture.createExpenseExtractor
import app.spent.capture.dismissCaptureNotification
import app.spent.data.CategoryItem
import app.spent.data.ExpenseSource
import app.spent.data.IntervalUnit
import app.spent.data.Money
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlin.time.Clock
import kotlin.time.Instant

data class ExpenseFormState(
    val expenseId: Long? = null,
    val capturedId: Long? = null,
    val amountText: String = "",
    val categoryId: Long? = null,
    val note: String = "",
    val merchant: String = "",
    val occurredAt: Instant = Clock.System.now(),
    val recurring: Boolean = false,
    val intervalUnit: IntervalUnit = IntervalUnit.MONTH,
    val intervalCount: String = "1",
    /** Set when editing an expense that was generated by a recurring rule (an occurrence of a series). */
    val recurringRuleId: Long? = null,
    val categories: List<CategoryItem> = emptyList(),
    val currencySymbol: String = "$",
    val amountError: Boolean = false,
    /** AI is reading the notification — fields are loading. */
    val aiSuggesting: Boolean = false,
    /** This field currently holds an AI suggestion (cleared once the user edits it). */
    val aiSuggestedAmount: Boolean = false,
    val aiSuggestedMerchant: Boolean = false,
    val aiSuggestedCategory: Boolean = false,
    val source: ExpenseSource = ExpenseSource.MANUAL,
    val saved: Boolean = false,
) {
    val isEdit: Boolean get() = expenseId != null
}

class ExpenseFormViewModel : ViewModel() {
    private val expenses = ServiceLocator.expenseRepository
    private val categories = ServiceLocator.categoryRepository
    private val recurring = ServiceLocator.recurringRepository
    private val captured = ServiceLocator.capturedNotificationRepository

    private val _state = MutableStateFlow(
        ExpenseFormState(
            categories = categories.listActive(),
            currencySymbol = ServiceLocator.settings.currencySymbol,
        )
    )
    val state: StateFlow<ExpenseFormState> = _state.asStateFlow()

    /** Load an existing expense for editing. */
    fun loadExpense(id: Long) {
        val e = expenses.getById(id) ?: return
        _state.value = _state.value.copy(
            expenseId = e.id,
            amountText = formatAmountForEdit(e.amountMinor),
            categoryId = e.categoryId,
            note = e.note.orEmpty(),
            merchant = e.merchant.orEmpty(),
            occurredAt = e.occurredAt,
            source = e.source,
            recurringRuleId = e.recurringRuleId,
            // Editing a saved expense — never an AI suggestion, so clear any leftover loading/badges.
            recurring = false,
            amountError = false,
            aiSuggesting = false,
            aiSuggestedAmount = false,
            aiSuggestedMerchant = false,
            aiSuggestedCategory = false,
        )
    }

    // The regex values for this captured item, kept as the fallback for when AI is unavailable/fails.
    private var regexAmountText: String = ""
    private var regexMerchant: String = ""

    /**
     * Open the form for a captured notification. If it already produced an expense, edit that one
     * (no duplicate). When AI is on, we do NOT surface the regex values — the form shows a loading
     * state while Gemini Nano reads the notification, then fades the AI values in. When AI is off or
     * unavailable, we fall back to the deterministic regex values (no loading, no AI badge).
     */
    fun loadCaptured(capturedId: Long) {
        val item = captured.getById(capturedId) ?: return
        item.expenseId?.let { existing ->
            loadExpense(existing) // already saved — edit, don't recreate
            return
        }
        captured.markRead(capturedId)
        regexAmountText = item.amountMinor?.let { formatAmountForEdit(it) } ?: ""
        regexMerchant = item.merchant.orEmpty()

        if (ServiceLocator.settings.aiEnabled) {
            // AI path: blank the fields and show a loading state until Nano returns.
            _state.value = _state.value.copy(
                capturedId = capturedId,
                amountText = "",
                merchant = "",
                categoryId = null,
                occurredAt = item.postedAt,
                source = ExpenseSource.AUTO,
                aiSuggesting = true,
                aiSuggestedAmount = false,
                aiSuggestedMerchant = false,
                aiSuggestedCategory = false,
            )
            runAiAssist(item.appLabel, item.title, item.text)
        } else {
            _state.value = _state.value.copy(
                capturedId = capturedId,
                amountText = regexAmountText,
                merchant = regexMerchant,
                occurredAt = item.postedAt,
                source = ExpenseSource.AUTO,
                aiSuggesting = false,
                aiSuggestedAmount = false,
                aiSuggestedMerchant = false,
                aiSuggestedCategory = false,
            )
        }
    }

    private fun runAiAssist(appLabel: String, title: String, text: String) {
        viewModelScope.launch {
            val parsed = runCatching { createExpenseExtractor(aiEnabled = true).extract(appLabel, title, text) }
                .getOrNull()
            val cur = _state.value
            if (parsed != null && parsed.amountMinor > 0) {
                // Nano returned values — fill any field the user hasn't already typed into, and badge it.
                val takeAmount = cur.amountText.isBlank()
                val takeMerchant = cur.merchant.isBlank() && !parsed.merchant.isNullOrBlank()
                val resolvedCategory = CategoryMatcher.resolveByName(parsed.categoryGuess, cur.categories)
                val takeCategory = cur.categoryId == null && resolvedCategory != null
                _state.value = cur.copy(
                    amountText = if (takeAmount) formatAmountForEdit(parsed.amountMinor) else cur.amountText,
                    merchant = if (takeMerchant) parsed.merchant!! else cur.merchant,
                    categoryId = if (takeCategory) resolvedCategory else cur.categoryId,
                    aiSuggesting = false,
                    aiSuggestedAmount = takeAmount,
                    aiSuggestedMerchant = takeMerchant,
                    aiSuggestedCategory = takeCategory,
                )
            } else {
                // AI unavailable or failed — fall back to the regex values (no AI badge).
                _state.value = cur.copy(
                    amountText = cur.amountText.ifBlank { regexAmountText },
                    merchant = cur.merchant.ifBlank { regexMerchant },
                    aiSuggesting = false,
                )
            }
        }
    }

    // Editing a field by hand clears its "suggested by AI" badge.
    fun setAmount(text: String) { _state.value = _state.value.copy(amountText = text, amountError = false, aiSuggestedAmount = false) }
    fun setCategory(id: Long?) { _state.value = _state.value.copy(categoryId = id, aiSuggestedCategory = false) }
    fun setNote(text: String) { _state.value = _state.value.copy(note = text) }
    fun setMerchant(text: String) { _state.value = _state.value.copy(merchant = text, aiSuggestedMerchant = false) }
    fun setOccurredAt(instant: Instant) { _state.value = _state.value.copy(occurredAt = instant) }
    fun setRecurring(on: Boolean) { _state.value = _state.value.copy(recurring = on) }
    fun setIntervalUnit(unit: IntervalUnit) { _state.value = _state.value.copy(intervalUnit = unit) }
    fun setIntervalCount(text: String) { _state.value = _state.value.copy(intervalCount = text) }

    fun save() {
        val s = _state.value
        val amountMinor = Money.parseToMinor(s.amountText)
        if (amountMinor == null || amountMinor <= 0) {
            _state.value = s.copy(amountError = true)
            return
        }
        val now = Clock.System.now()
        viewModelScope.launch {
            when {
                s.isEdit -> {
                    expenses.update(
                        id = s.expenseId!!,
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        occurredAt = s.occurredAt,
                        source = s.source,
                    )
                    // Turning a one-off expense into a repeating one: keep this expense, start a
                    // forward-only series (no back-fill, no duplicate of the current occurrence).
                    if (s.recurring && s.recurringRuleId == null) {
                        recurring.addGoingForward(
                            amountMinor = amountMinor,
                            categoryId = s.categoryId,
                            note = s.note.ifBlank { null },
                            merchant = s.merchant.ifBlank { null },
                            unit = s.intervalUnit,
                            count = s.intervalCount.toLongOrNull()?.coerceAtLeast(1) ?: 1,
                            anchor = s.occurredAt,
                            now = now,
                        )
                        recurring.materializeDue(now)
                    }
                }
                s.recurring -> {
                    recurring.add(
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        unit = s.intervalUnit,
                        count = s.intervalCount.toLongOrNull()?.coerceAtLeast(1) ?: 1,
                        startAt = s.occurredAt,
                        endAt = null,
                    )
                    recurring.materializeDue(now)
                }
                else -> {
                    val newId = expenses.add(
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        occurredAt = s.occurredAt,
                        createdAt = now,
                        source = s.source,
                    )
                    s.capturedId?.let { cid ->
                        captured.linkExpense(cid, newId)
                        dismissCaptureNotification(cid)
                    }
                }
            }
            _state.value = _state.value.copy(saved = true)
        }
    }

    fun delete() {
        val id = _state.value.expenseId ?: return
        expenses.delete(id)
        _state.value = _state.value.copy(saved = true)
    }

    private fun formatAmountForEdit(amountMinor: Long): String {
        val major = amountMinor / 100
        val minor = (amountMinor % 100).toString().padStart(2, '0')
        return if (amountMinor % 100 == 0L) major.toString() else "$major.$minor"
    }
}
