@file:OptIn(kotlin.time.ExperimentalTime::class)

package app.expensetracker.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import app.expensetracker.ServiceLocator
import app.expensetracker.capture.CategoryMatcher
import app.expensetracker.capture.createExpenseExtractor
import app.expensetracker.capture.dismissCaptureNotification
import app.expensetracker.data.CategoryItem
import app.expensetracker.data.ExpenseSource
import app.expensetracker.data.IntervalUnit
import app.expensetracker.data.Money
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlin.time.Clock
import kotlin.time.Instant

/** A form field the on-device AI can fill in. */
enum class AiField { AMOUNT, MERCHANT, CATEGORY }

/**
 * The AI-assist phase for the expense form — one value instead of a handful of booleans that have to
 * be flipped in lockstep. Drives the loading shimmer and the per-field "suggested" badges, and makes
 * impossible combinations (loading *and* suggested, etc.) unrepresentable.
 */
sealed interface AiAssist {
    /** No AI involved — manual entry or the regex fallback. */
    data object Inactive : AiAssist

    /** Gemini Nano is reading the notification; fields are loading. */
    data object Loading : AiAssist

    /** Nano returned; [fields] still hold its suggestions (until the user edits them). */
    data class Suggested(val fields: Set<AiField>) : AiAssist

    fun suggests(field: AiField): Boolean = this is Suggested && field in fields

    /** Drop [field] from the suggestion set (the user just edited it by hand). */
    fun without(field: AiField): AiAssist = if (this is Suggested) Suggested(fields - field) else this
}

data class ExpenseFormState(
    val expenseId: Long? = null,
    val capturedId: Long? = null,
    val amountText: String = "",
    val categoryId: Long? = null,
    val note: String = "",
    val merchant: String = "",
    val occurredAt: Instant = Clock.System.now(),
    val recurring: Boolean = false,
    val intervalUnit: IntervalUnit = IntervalUnit.MONTH,
    val intervalCount: String = "1",
    /** Set when editing an expense that was generated by a recurring rule (an occurrence of a series). */
    val recurringRuleId: Long? = null,
    val categories: List<CategoryItem> = emptyList(),
    val currencySymbol: String = "$",
    val amountError: Boolean = false,
    val aiAssist: AiAssist = AiAssist.Inactive,
    val source: ExpenseSource = ExpenseSource.MANUAL,
    val saved: Boolean = false,
) {
    val isEdit: Boolean get() = expenseId != null

    // Derived view flags — keep the screen reading simple booleans off the single AiAssist state.
    val aiSuggesting: Boolean get() = aiAssist is AiAssist.Loading
    val aiSuggestedAmount: Boolean get() = aiAssist.suggests(AiField.AMOUNT)
    val aiSuggestedMerchant: Boolean get() = aiAssist.suggests(AiField.MERCHANT)
    val aiSuggestedCategory: Boolean get() = aiAssist.suggests(AiField.CATEGORY)
}

class ExpenseFormViewModel : ViewModel() {
    private val expenses = ServiceLocator.expenseRepository
    private val categories = ServiceLocator.categoryRepository
    private val recurring = ServiceLocator.recurringRepository
    private val captured = ServiceLocator.capturedNotificationRepository

    private val _state = MutableStateFlow(
        ExpenseFormState(
            categories = categories.listActive(),
            currencySymbol = ServiceLocator.settings.currencySymbol,
        )
    )
    val state: StateFlow<ExpenseFormState> = _state.asStateFlow()

    /** Load an existing expense for editing. */
    fun loadExpense(id: Long) {
        val e = expenses.getById(id) ?: return
        _state.value = _state.value.copy(
            expenseId = e.id,
            amountText = Money.toEditString(e.amountMinor),
            categoryId = e.categoryId,
            note = e.note.orEmpty(),
            merchant = e.merchant.orEmpty(),
            occurredAt = e.occurredAt,
            source = e.source,
            recurringRuleId = e.recurringRuleId,
            // Editing a saved expense — never an AI suggestion, so clear any leftover loading/badges.
            recurring = false,
            amountError = false,
            aiAssist = AiAssist.Inactive,
        )
    }

    /**
     * Open the form for a captured notification. If it already produced an expense, edit that one
     * (no duplicate). When AI is on, we do NOT surface the regex values — the form shows a loading
     * state while Gemini Nano reads the notification, then fades the AI values in. When AI is off or
     * unavailable, we fall back to the deterministic regex values (no loading, no AI badge).
     */
    fun loadCaptured(capturedId: Long) {
        val item = captured.getById(capturedId) ?: return
        item.expenseId?.let { existing ->
            loadExpense(existing) // already saved — edit, don't recreate
            return
        }
        launchIo { captured.markRead(capturedId) }
        // Regex fallback for this item, scoped to this load — passed into the AI coroutine so it can't
        // leak into a later captured item opened before the AI call returns.
        val regexAmount = item.amountMinor?.let { Money.toEditString(it) } ?: ""
        val regexMerchant = item.merchant.orEmpty()

        if (ServiceLocator.settings.aiEnabled) {
            // AI path: blank the fields and show a loading state until Nano returns.
            _state.value = _state.value.copy(
                capturedId = capturedId,
                amountText = "",
                merchant = "",
                categoryId = null,
                occurredAt = item.postedAt,
                source = ExpenseSource.AUTO,
                aiAssist = AiAssist.Loading,
            )
            runAiAssist(item.appLabel, item.title, item.text, regexAmount, regexMerchant)
        } else {
            _state.value = _state.value.copy(
                capturedId = capturedId,
                amountText = regexAmount,
                merchant = regexMerchant,
                occurredAt = item.postedAt,
                source = ExpenseSource.AUTO,
                aiAssist = AiAssist.Inactive,
            )
        }
    }

    private fun runAiAssist(appLabel: String, title: String, text: String, regexAmount: String, regexMerchant: String) {
        viewModelScope.launch {
            val parsed = runCatching { createExpenseExtractor(aiEnabled = true).extract(appLabel, title, text) }
                .getOrNull()
            val cur = _state.value
            if (parsed != null && parsed.amountMinor > 0) {
                // Nano returned values — fill any field the user hasn't already typed into, and badge it.
                val takeAmount = cur.amountText.isBlank()
                val takeMerchant = cur.merchant.isBlank() && !parsed.merchant.isNullOrBlank()
                val resolvedCategory = CategoryMatcher.resolveByName(parsed.categoryGuess, cur.categories)
                val takeCategory = cur.categoryId == null && resolvedCategory != null
                val suggested = buildSet {
                    if (takeAmount) add(AiField.AMOUNT)
                    if (takeMerchant) add(AiField.MERCHANT)
                    if (takeCategory) add(AiField.CATEGORY)
                }
                _state.value = cur.copy(
                    amountText = if (takeAmount) Money.toEditString(parsed.amountMinor) else cur.amountText,
                    merchant = if (takeMerchant) parsed.merchant else cur.merchant,
                    categoryId = if (takeCategory) resolvedCategory else cur.categoryId,
                    aiAssist = AiAssist.Suggested(suggested),
                )
            } else {
                // AI unavailable or failed — fall back to the regex values (no AI badge).
                _state.value = cur.copy(
                    amountText = cur.amountText.ifBlank { regexAmount },
                    merchant = cur.merchant.ifBlank { regexMerchant },
                    aiAssist = AiAssist.Inactive,
                )
            }
        }
    }

    // Editing a field by hand clears its "suggested by AI" badge.
    fun setAmount(text: String) { _state.value = _state.value.copy(amountText = text, amountError = false, aiAssist = _state.value.aiAssist.without(AiField.AMOUNT)) }
    fun setCategory(id: Long?) { _state.value = _state.value.copy(categoryId = id, aiAssist = _state.value.aiAssist.without(AiField.CATEGORY)) }
    fun setNote(text: String) { _state.value = _state.value.copy(note = text) }
    fun setMerchant(text: String) { _state.value = _state.value.copy(merchant = text, aiAssist = _state.value.aiAssist.without(AiField.MERCHANT)) }
    fun setOccurredAt(instant: Instant) { _state.value = _state.value.copy(occurredAt = instant) }
    fun setRecurring(on: Boolean) { _state.value = _state.value.copy(recurring = on) }
    fun setIntervalUnit(unit: IntervalUnit) { _state.value = _state.value.copy(intervalUnit = unit) }
    fun setIntervalCount(text: String) { _state.value = _state.value.copy(intervalCount = text) }

    fun save() {
        val s = _state.value
        val amountMinor = Money.parseToMinor(s.amountText)
        if (amountMinor == null || amountMinor <= 0) {
            _state.value = s.copy(amountError = true)
            return
        }
        val now = Clock.System.now()
        launchIo {
            when {
                s.isEdit -> {
                    expenses.update(
                        id = s.expenseId!!,
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        occurredAt = s.occurredAt,
                        source = s.source,
                    )
                    // Turning a one-off expense into a repeating one: keep this expense, start a
                    // forward-only series (no back-fill, no duplicate of the current occurrence).
                    if (s.recurring && s.recurringRuleId == null) {
                        recurring.addGoingForward(
                            amountMinor = amountMinor,
                            categoryId = s.categoryId,
                            note = s.note.ifBlank { null },
                            merchant = s.merchant.ifBlank { null },
                            unit = s.intervalUnit,
                            count = s.intervalCount.toLongOrNull()?.coerceAtLeast(1) ?: 1,
                            anchor = s.occurredAt,
                            now = now,
                        )
                        recurring.materializeDue(now)
                    }
                }
                s.recurring -> {
                    recurring.add(
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        unit = s.intervalUnit,
                        count = s.intervalCount.toLongOrNull()?.coerceAtLeast(1) ?: 1,
                        startAt = s.occurredAt,
                        endAt = null,
                    )
                    recurring.materializeDue(now)
                }
                else -> {
                    val newId = expenses.add(
                        amountMinor = amountMinor,
                        categoryId = s.categoryId,
                        note = s.note.ifBlank { null },
                        merchant = s.merchant.ifBlank { null },
                        occurredAt = s.occurredAt,
                        createdAt = now,
                        source = s.source,
                    )
                    s.capturedId?.let { cid ->
                        captured.linkExpense(cid, newId)
                        dismissCaptureNotification(cid)
                    }
                }
            }
            _state.value = _state.value.copy(saved = true)
        }
    }

    fun delete() {
        val id = _state.value.expenseId ?: return
        launchIo {
            expenses.delete(id)
            // Detach the source notification (if any) so it doesn't keep pointing at a deleted expense.
            captured.clearExpenseLink(id)
            _state.value = _state.value.copy(saved = true)
        }
    }
}
